[package]
name = "omage-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rayon = "1.5.1"
slog = "2.7.0"
slog-term = "2.8.1"
slog-async = "2.7.0"
directories = "4.0.1"
chrono = "0.4.19"